server:
  port: 8080
spring:
  application:
    name: "FinanceLab"
  devtools:
    add-properties: false
  webflux:
    base-path: "/api/v1/financeapp"
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
    active: local
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
routes:
  paths:
    listUsers: "/users"
    createUser: "/user"
    updateUser: "/user"
    deleteUser: "/user/{id}"
    listIncomes: "/incomes"
    createIncome: "/income"
    updateIncome: "/income"
    deleteIncome: "/income/{id}"
    listExpenses: "/expenses"
    createExpense: "/expense"
    updateExpense: "/expense"
    deleteExpense: "/expense/{id}"
    listGoals: "/goals"
    createGoal: "/goal"
    updateGoal: "/goal"
    deleteGoal: "/goal/{id}"
    listCategories: "/categories"
    createCategory: "/category"
    listSubcategories: "/subcategories"
    createSubcategory: "/subcategory"
    downloadFile: "/download-report"
    sendEmail: "/send-email"
aws:
  dynamodb:
    endpoint: "http://localhost:8010"
    threads: "10"
    tableNameUser: "FinanceLab_user"
    tableNameIncome: "FinanceLab_income"
    tableNameExpense: "FinanceLab_expense"
    tableNameGoal: "FinanceLab_goal"
    tableNameCategory: "FinanceLab_category"
  region: "us-east-1"
